version: '3.8'

services:
  dirt-detection-api:
    build: .
    container_name: dirt-detection-api
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - DIRT_THRESHOLD=5.0
      - CONFIDENCE_THRESHOLD=0.7
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s